#!/bin/sh
set -e
if [ "x$SSH_ORIGINAL_COMMAND" != "x" ]; then
exec '/Applications/git-annex.app/Contents/MacOS/runshell' git-annex-shell -c "$SSH_ORIGINAL_COMMAND"
else
exec '/Applications/git-annex.app/Contents/MacOS/runshell' git-annex-shell -c "$@"
fi
